# Generated by Django 5.2 on 2025-05-02 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("publicaciones", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="publicacion",
            table="publicaciones",
        ),
    ]
